upgrade lib versions
openTdataCH/ojp-adapter pull request #7
Opened 2023-12-28 12:39 UTC by phirzel

enable logging

2024-01-03 08:04 UTC, florianhof commented on ojp-adapter-integration/src/test/java/swiss/opentransportdata/ojp/adapter/v1/OJPAdapterAccessTest.java
> +            ojpAdapter;
(komische Formattierung mit 2 Zeilen)

2024-01-03 08:44 UTC, florianhof requested changes

2024-01-03 08:44 UTC, florianhof commented on ojp-adapter-integration/src/test/java/swiss/opentransportdata/ojp/adapter/v1/OJPAdapterAccessTest.java
> + * Integration-Test..
(komische Formattierung)

2024-01-03 08:44 UTC, florianhof commented on ojp-adapter/src/main/resources/logback.xml
> +            <!--pattern>%highlight(%-5level) %logger{36} %msg %n</pattern-->
Datei komplett weglöschen oder in src/test verschieben!

2024-01-03 08:44 UTC, florianhof commented on ojp-adapter/pom.xml
>              <artifactId>logback-classic</artifactId>
eigentlich kann der Scope reduziert werden: 
`<scope>test</scope>`

2024-01-03 10:21 UTC, florianhof approved these changes
New commit from me to adress the feedbacks.

2024-01-03 10:26 UTC, merged

2024-01-22 14:26 UTC, phirzel commented on ojp-adapter-integration/src/test/java/swiss/opentransportdata/ojp/adapter/v1/OJPAdapterAccessTest.java
> +            ojpAdapter;
(will be fixed by next PR)

2024-01-22 14:27 UTC, phirzel commented on ojp-adapter-integration/src/test/java/swiss/opentransportdata/ojp/adapter/v1/OJPAdapterAccessTest.java
> + * Integration-Test..
(will be fixed with next PR)